### PR TITLE
ABOUT ME

### PR DESCRIPTION
**Pull request by AMANSINGH1998**
:warning: This is a Pull Request Template :warning:

> Checkout all the things you've done by placing an \*x*\ within the square braces.

## Proposed Changes
- [ ] I've forked the repository.
- [ ] I've created a branch and made my changes in it. 
- [ ] I've read the [CODE OF CONDUCT](https://github.com/my-first-pr/hacktoberfest-2018/blob/master/CODE_OF_CONDUCT.md) and abide to it.
- [ ] I've read the [CONTRIBUTING.md](https://github.com/my-first-pr/hacktoberfest-2018/blob/master/CONTRIBUTING.md)
- [ ] I understand opening a PULL REQUEST doesn't mean it will be merged for sure.

### CODE REVIEW

**Comment by AMANSINGH1998** [comment]
THANK YOU for suggesting .I had push my own code and I thought it is comfortable.

**Comment by AMANSINGH1998** [comment]
DID THE REQUIRED CHANGES

**Comment by AMANSINGH1998** [comment]
THANK YOU for suggesting the changes ,did all the necessary changes

**Comment by joshcanhelp** [comment]
Please re-submit when you're ready 👍

**Pull request closed without merging**
