### PR TITLE
Added my name to README.md

### PR DESCRIPTION
**Pull request by shoumikdey**
Fixes or introduces: 

## Proposed Changes

  -Added my name to the README.md
  -Added my profile under my name in README.md

### CODE REVIEW

**Comment by shoumikdey** [comment]
Can you tell me the conflicts please ?

**Comment by lukeoliff** [comment]
I can't even see them as the permissions on your branch don't let me.

**Comment by shoumikdey** [comment]
I think that, since I had edited the README.md file, it is generating all the conflicts. I too cannot find anything that I can change once again. It says "Only those with write access to this repository can merge pull requests."

**Comment by joshcanhelp** [comment]
@shoumikdey - You have a bunch of whitespace changes in there, which is probably causing the problem. I would pull `master`, rebase, fix conflicts, and push to this PR again. That or just kill your local branch, pull master, and push again to here. Make sure to put yourself in the right place, alphabetically!

**Comment by joshcanhelp** [comment]
@shoumikdey  - closing this for now. Please resubmit when you're ready. Thanks!

**Pull request closed without merging**
